name: Playwright Tests #this can be any nane
on:
  push: 
    branches: [ main ]
jobs: 
  playwrighttests: #this can be any nane
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.1-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #this is the github actions
      - name: Run test - whole thing
        run: |
          echo "Start the shopping store application"
          chmod +x ./shopping-store-linux-amd64 &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run test:ci


    #when git push occurs, this github actions pipeline will run